<?php

// Por favor, não avacalhe com o meu cartao de credito. Obrigado.
define("GMAPS_KEY", "AIzaSyB0_BwlzaJZcFbCN-sRUdU5gfNI48XLzy4");

define("CAMPO_ZERO", 0);
define("CAMPO_VAZIO", -1);
define("CAMPO_NULL", null);

define("SEM_COMPANHIA_AEREA_DEFINIDA", CAMPO_NULL);
define("SEM_AERONAVE_DEFINIDA", CAMPO_NULL);
define("SEM_PILOTO_DEFINIDO", CAMPO_NULL);
define("SEM_COPILOTO_DEFINIDO", CAMPO_NULL);
define("SEM_COMISSARIO_DEFINIDO", CAMPO_NULL);
define("SEM_CODIGO_VOO_DEFINIDO", CAMPO_NULL);
define("SEM_HORARIO_EMBARQUE_DEFINIDO", CAMPO_NULL);
define("SEM_DURACAO_PERCURSO_DEFINIDA", CAMPO_NULL);
define("SEM_PROGRAMA_DE_MILHAGEM_DEFINIDO", CAMPO_NULL);
define("SEM_CARGA_DEFINIDA", CAMPO_ZERO);

define("TAMANHO_REGISTRO", 6);

define("NOVA_INSTANCIA", 1);
define("ESCRITA_ATRIBUTO", 2);
define("LEITURA_ATRIBUTO", 3);

define("VELOCIDADE_MEDIA_VEICULO", 18);

// define("TAMANHO_RG", 8);
define('VAZIO', '');

DEFINE('PESO_FRANQUIA_BAGAGEM', 23);

define("PILOTO", 1);
define("COMISSARIO", 2);
