<?php

define("CAMPO_VAZIO", -1);

define("SEM_COMPANHIA_AEREA_DEFINIDA", CAMPO_VAZIO);
define("SEM_AERONAVE_DEFINIDA", CAMPO_VAZIO);
define("SEM_PILOTO_DEFINIDO", CAMPO_VAZIO);
define("SEM_COPILOTO_DEFINIDO", CAMPO_VAZIO);
define("SEM_COMISSARIO_DEFINIDO", CAMPO_VAZIO);
define("SEM_CODIGO_VOO_DEFINIDO", CAMPO_VAZIO);

define("TAMANHO_REGISTRO", 6);


// define("TAMANHO_RG", 8);
define('VAZIO', '');

DEFINE('PESO_FRANQUIA_BAGAGEM', 23);

define("PILOTO", 1);
define("COMISSARIO", 2);
